{% set name = "conda-deny" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/quantco/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: dff87c61d532fb0e2344024afd58282927a939ea1d7ce56a11aeb010459029d2
build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses
    - pkg-config
  host:
    - openssl  # [unix]

test:
  commands:
    - conda-deny --help

about:
  home: https://github.com/quantco/conda-deny
  summary: 🔎🐍 A CLI tool to check your project's dependencies for license compliance
  license: BSD-3-Clause
  license_file:
    - LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - pavelzw
    - PaulKMueller
