{% set name = "conda-deny" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/quantco/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: ea654c9f8ca8c190eb0d53c5f1efb19da73ac4e67716f2b4232dae6c749a5011
build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses
    - pkg-config
  host:
    - openssl  # [unix]

test:
  commands:
    - conda-deny --help

about:
  home: https://github.com/quantco/conda-deny
  summary: 🔎🐍 A CLI tool to check your project's dependencies for license compliance
  license: BSD-3-Clause
  license_file:
    - LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - pavelzw
    - PaulKMueller
