{% set name = "conda-deny" %}
{% set version = "0.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/quantco/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: f75e9a5d171bee5ff7d2143610c1340eef7a39b2089cf651402171a24cc02c7a
build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses
    - pkg-config
  host:
    - openssl  # [unix]

test:
  commands:
    - conda-deny --help

about:
  home: https://github.com/quantco/conda-deny
  summary: 🔎🐍 A CLI tool to check your project's dependencies for license compliance
  license: BSD-3-Clause
  license_file:
    - LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - pavelzw
    - PaulKMueller
