{% set name = "conda-deny" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/quantco/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: d34c5b5d25b154879b9546b1c67d855b3901db6c4fe3417798dc8e2d053c2be5
build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses
  host:
    - openssl  # [unix]

test:
  commands:
    - conda-deny --help

about:
  home: https://github.com/quantco/conda-deny
  summary: 🔎🐍 A CLI tool to check your project's dependencies for license compliance
  license: BSD-3-Clause
  license_file:
    - LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - pavelzw
    - PaulKMueller
