schema_version: 1

context:
  name: conda-deny
  version: "0.5.3"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/quantco/${{ name }}/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 91f49a91cada1c0fab5ae3b6576c5d269b02dd9b62e79a1bf0e5250523dc4b8e

build:
  number: 1

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses
    - cargo-auditable
    - pkg-config
  host:
    - if: unix
      then: openssl

tests:
  - script:
      - conda-deny --help

about:
  summary: 🔎🐍 A CLI tool to check your project's dependencies for license compliance\""
  license: BSD-3-Clause
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  homepage: https://github.com/quantco/conda-deny

extra:
  recipe-maintainers:
    - pavelzw
    - PaulKMueller
