schema_version: 1

context:
  name: conda-deny
  version: "0.5.4"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/quantco/${{ name }}/archive/refs/tags/v${{ version }}.tar.gz
  sha256: ee382067a667855a245170d3093921264f354ad47cb90c6e792ae935b03a099e

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses
    - cargo-auditable
    - pkg-config
  host:
    - if: unix
      then: openssl

tests:
  - script:
      - conda-deny --help

about:
  summary: 🔎🐍 A CLI tool to check your project's dependencies for license compliance\""
  license: BSD-3-Clause
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  homepage: https://github.com/quantco/conda-deny
  repository: https://github.com/quantco/conda-deny

extra:
  recipe-maintainers:
    - pavelzw
    - PaulKMueller
