schema_version: 1

context:
  name: conda-deny
  version: "0.5.9"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/quantco/${{ name }}/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 80328c89d9eca7191b46bfdd25fc13e6e6d35881ffb66d56fa10b7134a29d9ca

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses
    - cargo-auditable
    - pkg-config
  host:
    - if: unix
      then: openssl

tests:
  - script:
      - conda-deny --help

about:
  summary: 🔎🐍 A CLI tool to check your project's dependencies for license compliance
  license: BSD-3-Clause
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  homepage: https://github.com/quantco/conda-deny
  repository: https://github.com/quantco/conda-deny

extra:
  recipe-maintainers:
    - pavelzw
    - PaulKMueller
